version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tomw1808/laravelproject
    container_name: app
    restart: unless-stopped
    networks:
      - LAN
    volumes:
    - ./:/var/www
    - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: tomw1808/nginx
    container_name: web_server
    restart: unless-stopped
    networks:
      - LAN
    environment:
      DB_HOST: db
      DB_PASSWORD: secret
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:5.7.22
    container_name: db
    networks:
      - LAN
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs
networks:
  LAN:
    driver: bridge
    name: apim2_LAN

volumes:
  dbdata:
    driver: local


